fullnameOverride: acme

replicaCount: 1

profile: default

namespace: default

image:
  repository: acme
  tag: latest
  pullPolicy: Always

dockerRegistrySecret: regcred

labels: {}
annotations: {}

pod:
  labels: {}
  annotations: {}

pdb: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations: {}
  labels: {}

ingress:
  enabled: true
  subdomain: acme
  basedomain: 127.0.0.1.nip.io
  hosts: {}
  # hosts:
  #   - acme.opsnow.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  labels: {}

autoscaling:
  enabled: true
  min: 1
  max: 5
  cpu: 80
  mem: 80
  custom: {}
  # request: "15000m"

resources:
  requests:
    cpu: 250m
    memory: 1024Mi
  limits:
    cpu: 300m
    memory: 1252Mi

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

# livenessProbe:
#   exec:
#     command:
#     - cat
#     - /tmp/healthy
#   initialDelaySeconds: 15
#   periodSeconds: 10
# livenessProbe:
#   tcpSocket:
#     port: 8080
#   initialDelaySeconds: 15
#   periodSeconds: 10

# hostNetwork: true
# dnsPolicy: Default

nodeSelector: {}

tolerations: []

affinity: {}

env: {}
  # - name: MESSAGE
  #   value: "hello world"

java:
  options: "-XX:InitialRAMPercentage=40.0 -XX:MaxRAMPercentage=80.0"

pinpoint:
  enabled: false
  sampling: 1
  collectorIp: pinpoint-collector.monitor.svc.cluster.local

configmap:
  enabled: false
  data: {}
    # MESSAGE: "hello world"

secret:
  enabled: false
  data: {}
    # SECRET: "c2VjcmV0IHdvcmxkCg=="

canary: {}
#  enabled: false
#  revertOnDeletion: false
#  provider: nginx
#  progressDeadlineSeconds: 90
#  ## Canary
#  analysis:
#    interval: 10s
#    threshold: 10
#    maxWeight: 50
#    stepWeight: 5
#    metrics:
#      - name: request-success-rate
#        thresholdRange:
#          min: 99
#        interval: 2m
#    webhooks:
#      - name: load-test
#        url: http://flagger-loadtester.devops/
#        timeout: 5s
#        metadata:
#          cmd: "hey -z 1m -q 10 -c 2 https://{{ first .Values.ingress.hosts }}"